services:
  api:
    build: .
    container_name: xbrl_tag_recommender_api
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
